exports.NounInflector = require('./inflectors/noun_inflector')
exports.NounInflectorFr = require('./inflectors/fr/noun_inflector')
exports.NounInflectorJa = require('./inflectors/ja/noun_inflector')
exports.PresentVerbInflector = require('./inflectors/present_verb_inflector')
exports.CountInflector = require('./inflectors/count_inflector')
